version: 0.2  
phases:  
  install:
    commands:
      - aws cloudformation package --template-file quotes-template.yaml --s3-bucket codepipeline-us-west-1-325429776351 --output-template-file quotes.yaml
artifacts:  
  type: zip
  files:
    - quotes.yaml