AWSTemplateFormatVersion: '2010-09-09'  
Transform: 'AWS::Serverless-2016-10-31'  
Description: Lambda - Quotes  

# Parameters:
#   BucketNamePhotos:
#     Type: String
#     Default: 'smartalbum.photos-test'
#     AllowedPattern: "[A-Za-z0-9-]+"
#   FunctionNameLF1:
#     Type: String
#     Default: Assignment3-LF1-test  # Don't change this
#     AllowedValues: 
#       - Assignment3-LF1-test
#     AllowedPattern: "[A-Za-z0-9-]+"

Resources:  
  developerlambdaquotes:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Assignment3-LF1-test
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Description: Lambda - Quotes
      MemorySize: 128
      Timeout: 7
      Layers:
        - !Ref libs
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/administrator-test
  libs:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: elasticsearch-lib
      Content:
        S3Bucket: layer.lambda.aws
        S3Key: elasticsearch.zip
      CompatibleRuntimes:
        - python3.8

  S3BucketPhotos:
    DependsOn:
      - ConfigLambdaPermission
    Type: AWS::S3::Bucket
    Properties:
      BucketName: smartalbum.photos-test
      AccessControl: PublicReadWrite
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Function: !GetAtt developerlambdaquotes.Arn
  S3BucketPoliyPhotos:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3BucketPhotos
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource:
              'Fn::Join':
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3BucketPhotos
                  - /*
            Principal: '*'

  ConfigLambdaPermission:
      Type: "AWS::Lambda::Permission"
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !Ref developerlambdaquotes
        Principal: s3.amazonaws.com
        SourceArn: 'arn:aws:s3:::smartalbum.photos-test'
