AWSTemplateFormatVersion: '2010-09-09'  
Transform: 'AWS::Serverless-2016-10-31'  
Description: Lambda - Quotes  
Resources:  
  developerlambdaquotes:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Assignment3-LF1
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Description: Lambda - Quotes
      MemorySize: 128
      Timeout: 7
      Role: >-
        arn:aws:iam::026298698340:role/service-role/LF2-Python-role-opu4cuho